swagger: '2.0'
info:
  title: walletscan-demo
  description: Walletscan Demo API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /scan:
    get:
      summary: Gets holistic information about an ethereum wallet
      operationId: hello
      x-google-backend:
        address: https://us-central1-walletscan-354022.cloudfunctions.net/walletscanV0
      responses:
        '200':
          description: A successful response